### ISSUE TITLE
## ERRORS in dependency circuithub/elm-html-shorthand 7.0.0 ##

### ISSUE THREAD

**Issue by NigelThorne** [twopoint718/elmchat#3]
When building this project I get the following error: 

nigel@nigel-Satellite-P850:~/elmchat$ elm-package install 
Some new packages are needed. Here is the upgrade plan.

  Install:
    circuithub/elm-bootstrap-html 6.3.1
    circuithub/elm-html-extra 1.4.0
    circuithub/elm-html-shorthand 7.0.0
    elm-lang/core 2.1.0
    evancz/elm-html 3.0.0
    evancz/elm-http 1.0.0
    evancz/virtual-dom 1.2.3

Do you approve of this plan? (y/n) y
Downloading circuithub/elm-bootstrap-html
Downloading circuithub/elm-html-extra
Downloading circuithub/elm-html-shorthand
Downloading elm-lang/core
Downloading evancz/elm-html
Downloading evancz/elm-http
Downloading evancz/virtual-dom
Packages configured successfully!
nigel@nigel-Satellite-P850:~/elmchat$ elm-make Main.elm 
## ERRORS in dependency circuithub/elm-html-shorthand 7.0.0

This error probably means that the 'circuithub/elm-html-shorthand' has some
package constraint that is too permissive. You should definitely inform the
maintainer to get this fixed and save other people from this pain.

In the meantime, you can attempt to artificially constrain things by adding
some extra constraints to your elm-package.json though that is not
the long term solution.

Detected errors in 1 module.

**Comment by NigelThorne** [comment]
I don't understand why it's trying to use version 7 when the elm-package.json references 8.

**Comment by twopoint718** [comment]
Hmmm, I'll investigate this. But it looks like one of the packages that `elmchat` depends on may have a problem. Thanks for letting me know!

**Comment by twopoint718** [comment]
I've created an issue upstream: circuithub/elm-html-shorthand#4 that, I hope, is relevant. I fiddled around with the package constraints on this and I couldn't find one that worked for me. I'll have more time to look at it after Strange Loop.

**Comment by twopoint718** [comment]
No new information here, but I'm adding the mailing list discussion for anyone following along: https://groups.google.com/forum/?fromgroups#!topic/elm-discuss/FKl884AxRfE

**Comment by twopoint718** [comment]
After fiddling with the versions for a while, it seemed like the bootstrap package was a blocker. And it also sounds like it may not be updated for a bit, in the mean time, I've just removed this app's dependency on that package. Commit c092208 should build for you now.
